declare module '*.png';
declare module '*.jpg';
declare module '*.webp';
declare module '*.gif';
declare module '*.svg';
declare module '*.mp4';
declare module '*.webm';
declare module '*.ogg';
declare module '*.mov';
